### ISSUE TITLE
Can't find the gstreamer variables

### ISSUE THREAD

**Issue by somini** [tomvanbraeckel/3dfsb#1]
I'm trying to compile using the script but there's an error:

```
3dfsb.c:39:21: fatal error: gst/gst.h: No such file or directory
```

I installed all the necessary dependencies, and 

```
$ apt contains gst.h
libgstreamer0.10-dev: /usr/include/gstreamer-0.10/gst/gst.h
```

shows the file is there.

**Comment by tomvanbraeckel** [comment]
Hmmm, I'm using GStreamer 1.0 instead of the (old) GStreamer 0.10, could that be the cause? In the meantime, I'll clarify that in the README and I'll try reproducing your issue on a different machine...

**Comment by somini** [comment]
Hmm, that's probably it. The readme indicates otherwise.
I'll retest later when I get home.

**Comment by tomvanbraeckel** [comment]
You are right, and the README has now been updated. Thanks a lot for testing and feedback, just let me know if I can be of any more assistance!

**Comment by tomvanbraeckel** [comment]
Any luck?

PS: the compile.sh script has been improved a lot, and should now work on all Intel 32 and 64 bit Linux installations. So please try it out, and let me know!

**Comment by somini** [comment]
Sorry, just couldn't find the time.
Today as soon as I get home, I promise! :)

**Comment by somini** [comment]
```
3dfsb.c:56:41: fatal error: gst/gl/x11/gstgldisplay_x11.h: No such file or directory
```

apt contains can't find it anywhere, perhaps it's something I overlooked.

**Comment by tomvanbraeckel** [comment]
Please update your sources to the latest version, that header file is no longer used...

**Comment by somini** [comment]
Sorry for the big delay, I had no internet access this weekend. It's working now, compiles with just a bunch of warnings.

**Comment by tomvanbraeckel** [comment]
Thanks a lot for the feedback! Yes, the warnings will be handled soon :-)
