### ISSUE TITLE
Compiling issue in Ubuntu 15.04

### ISSUE THREAD

**Issue by maidenone** [tomvanbraeckel/3dfsb#13]
Compiling...input.c:5:17: fatal error: xdo.h: No such file or directory
 #include <xdo.h>

solved by: sudo apt-get install libxdo-dev

Compiling...input.c:6:34: fatal error: X11/extensions/XTest.h: No such file or directory
 #include <X11/extensions/XTest.h>

solved by: sudo apt-get install libxtst-dev 

Please update the ubuntu commands in readme ;)

**Comment by tomvanbraeckel** [comment]
Done in commit 4b647a13be65c04b13b9d078e47cc550108a2d68 - thanks!
