### ISSUE TITLE
Magic Issues in Arch

### ISSUE THREAD

**Issue by ImNtReal** [tomvanbraeckel/3dfsb#2]
This doesn't seem to want to build against the magic.h provided by file-5.21-3 in Arch Linux.

/tmp/ccxfxlCV.o: In function `ende':
/home/jmpugh/AUR/direvent/src/3dfsb-1.0-rc1/3dfsb.c:427: undefined reference to`magic_close'
/tmp/ccxfxlCV.o: In function `get_file_type':
/home/jmpugh/AUR/direvent/src/3dfsb-1.0-rc1/3dfsb.c:468: undefined reference to`magic_file'
/tmp/ccxfxlCV.o: In function `main':
/home/jmpugh/AUR/direvent/src/3dfsb-1.0-rc1/3dfsb.c:3754: undefined reference to`magic_open'
/home/jmpugh/AUR/direvent/src/3dfsb-1.0-rc1/3dfsb.c:3755: undefined reference to `magic_load'
collect2: error: ld returned 1 exit status

**Comment by pouar** [comment]
add "-lmagic" to link flags

**Comment by ImNtReal** [comment]
That did it. Just needed to add it to the gcc line in the compile script. Thanks.

**Comment by tomvanbraeckel** [comment]
Thanks for your quick testing and feedback. The fix has been committed!

**Comment by tomvanbraeckel** [comment]
ImNtReal: thanks for working on the Arch package for this! Just a heads up; on https://aur.archlinux.org/packages/3dfsb/ I noticed that libsmpeg is still in the dependency list and libmagic is not. Also, version 1.0 (without -rc1) is now available and the compile.patch should not longer be needed anymore. Let me know if I can do anything else!

**Comment by tomvanbraeckel** [comment]
By the way, the compile.sh script has been improved a lot, and should now work on all Intel 32 and 64 bit Linux installations. So please try it out, and let me know!

**Comment by ImNtReal** [comment]
It does indeed appear to be fixed. I'll have to wait until later to test
the 1.0 build. the -rc1 build did some unusual things to my monitor setup.
Do you think you might move it to one of the make systems at some point?

**Comment by tomvanbraeckel** [comment]
Yes, moving to (at least) a Makefile is planned. I'm a bit weary of the advanced autotools based make systems and their scripts that make makefiles that make makefiles that compile the code, because they tend to cause more headaces than they solve, but I'll do it if that's what it takes to compile properly on all architectures.
