### ISSUE TITLE
a non-SDL version

### ISSUE THREAD

**Issue by snshn** [tomvanbraeckel/3dfsb#4]
How much work would you think it may be to get a non-SDL version (xlib only)?

Thants...

**Comment by tomvanbraeckel** [comment]
The dependency to SDL_image is easy to remove by using GStreamer for image handling (I already have this in my local development branch) but to remove the generic SDL dependency (used for setting resolution, creating a window,...) I have no idea... I guess it is doable, if there is a reason to...

May I ask why you want a non-SDL version? Perhaps that way I can prioritize and frame your question. Or provide an alternative solution...

**Comment by snshn** [comment]
Pure curiosity, also like seeing projects with as less dependencies as possible.

Thanks.
