### ISSUE TITLE
Unnecessary dependency on gtk

### ISSUE THREAD

**Issue by eduarrrd** [tomvanbraeckel/3dfsb#8]
All gtk related code is commented out except the include statement. It should be commented out as well.

If code is meant to stay, for debugging this could be an approach:

```
#ifdef GTK_DEBUG
#include gtk-stuff
#endif
...
#ifdef GTK_DEBUG
debug_using_gtk_funcs();
#endif
```

**Comment by tomvanbraeckel** [comment]
Fixed, thanks!
